# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: run_task

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "23 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 设置python3.9 / Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 安装依赖 / Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4 urllib3 lxml selenium requests qrcode
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: 安装其他软件 / install other sowtware
      run: |
        sudo apt update
        sudo apt install firefox firefox-geckodriver net-tools
    - name: 配置并运行 / config and run
      env:
        b_cookie: ${{secrets.cookies}}
      run: |
        echo ${{env.b_cookie}} > config/cookie.txt
#        sed -i "s/HEADLESS = False/HEADLESS = True/" config/config.py
        mkdir config/s_headless

        python3 checkCookie.py
        python3 main.py
